Appraisals/urls.py
from django.urls import path

from . import views

app_name = 'Appraisals'
urlpatterns = [
    path('user/', views.User_Appraisals, name='User_Appraisals'),
    path('manager/', views.Manager_Appraisals, name='Manager_Appraisals'),
    path('HR/', views.HR_Appraisals, name="HR_Appraisals"),

    path('allusers/Create_AppraisalCategory', views.Create_Appraisal_Category.as_view(), name="Create_Appraisal_Category"),
    path('allusers/<int:pk>/Create_User_Appraisal_List', views.Create_User_Appraisal_List.as_view(), name="Create_User_Appraisal_List"),

    path('allusers/<int:pk>/UpdateOverallAppraisal',views.update_Overall_Appraisal, name="Update_Overall_Appraisal"),
    #path('allusers/<int:pk>/<int:mk>/Update', views.UpdateAppraisal, name="Update_Appraisal"),

    path('allusers/<int:pk>/OverallAppraisal', views.Detail_Overall_Appraisal.as_view(), name="Detail_Overall_Appraisal"),
    path('allusers/<int:pk>/<int:mk>/UserAppraisal/', views.Detail_User_Appraisal_List.as_view(), name="Detail_User_Appraisal"),
    path('allusers/<int:pk>/<int:mk>/HRUserAppraisal/', views.Detail_HRUser_Appraisal_List.as_view(), name="HRDetail_User_Appraisal"),

    path('allusers/<int:pk>/DeleteUserAppraisal', views.Delete_User_Appraisal_List.as_view(), name="Delete_User_Appraisal"),
    path('allusers/<int:pk>/DeleteOverallAppraisal', views.Delete_Overall_Appraisal.as_view(), name='Delete_Overall_Appraisal'),

    path('allusers/<int:pk>/EtM/AppraisalFlow', views.EtM_User_Appraisal_List.as_view(), name='EtM_Appraisal'),
    path('allusers/<int:pk>/MtE/AppraisalFlow', views.MtE_User_Appraisal_List.as_view(), name='MtE_Appraisal'),
    path('allusers/<int:pk>/MtS1BE', views.MtS1BE_User_Appraisal_List.as_view(), name='MtS1BE_Appraisal'),

    path('allusers/<int:pk>/S1BEtS1BM', views.S1BEtS1BM_User_Appraisal_List.as_view(), name='S1BEtS1BM_Appraisal'),
    path('allusers/<int:pk>/S1BMtS1BR', views.S1BMtS1BR_User_Appraisal_List.as_view(), name='S1BMtS1BR_Appraisal'),
    path('allusers/<int:pk>/S1BRtS1BM', views.S1BRtS1BM_User_Appraisal_List.as_view(), name='S1BRtS1BM_Appraisal'),
    path('allusers/<int:pk>/S1BMtS2E', views.S1BMtS2E_User_Appraisal_List.as_view(), name='S1BMtS2E_Appraisal'),

    path('allusers/<int:pk>/S2EtS2M', views.S2EtS2M_User_Appraisal_List.as_view(), name='S2EtS2M_Appraisal'),
    path('allusers/<int:pk>/S2MtApp', views.S2MtApp_User_Appraisal_List.as_view(), name='S2MtApp_Appraisal'),
    path('allusers/<int:pk>/ApptS2M', views.ApptS2M_User_Appraisal_List.as_view(), name='ApptS2M_Appraisal'),
    path('allusers/<int:pk>/S2MtAppR', views.S2MtAppR_User_Appraisal_List.as_view(), name='S2MtAppR_Appraisal'),
   # path('allusers/<int:pk>/<int:mk>/Update1', views.updateAppraisal2.as_view(), name="Update_Appraisal1")
    path('allusers/<int:pk>/UpdateMidYear/UpdateG/', views.UpdateMidAppraisalG, name="Update_MIDAppraisalG"),
    path('allM/<int:pk>/UpdateMidYear/UpdateG/', views.UpdateMidAppraisalG_M, name="Update_MIDAppraisalG_M"),

    path('allusers/<int:pk>/Update/UpdateS/UpdateC/UpdateG/', views.UpdateAppraisalG, name="Update_AppraisalG"),
    path('allusers/<int:pk>/Update/UpdateS/UpdateC/', views.UpdateAppraisalC, name='Update_AppraisalC'),
    path('allusers/<int:pk>/Update/UpdateS/', views.UpdateAppraisalS, name='Update_AppraisalS'),
    path('allusers/<int:pk>/Update/Career', views.createCareerDiscussion, name='Update_AppraisalCareer'),
    path('allusers/<int:pk>/Update/', views.Update_Appraisal, name='Update_Appraisal'),

    path('allM/<int:pk>/Update/UpdateS/UpdateC/UpdateG/', views.UpdateAppraisalG_M, name="Update_AppraisalG_M"),
    path('allM/<int:pk>/Update/UpdateS/UpdateC/', views.UpdateAppraisalC_M, name='Update_AppraisalC_M'),
    path('allM/<int:pk>/Update/UpdateS/', views.UpdateAppraisalS_M, name='Update_AppraisalS_M'),
    path('allM/<int:pk>/Update/Career', views.UpdateAppraisalCareer_M, name='Update_AppraisalCareer_M'),
    path('allM/<int:pk>/Update/', views.Update_Appraisal_M, name='Update_Appraisal_M'),

    path('allHR/<int:pk>/Update/UpdateS/UpdateC/UpdateG/', views.UpdateAppraisalG_B, name="Update_AppraisalG_B"),
    path('allHR/<int:pk>/Update/UpdateS/UpdateC/', views.UpdateAppraisalC_B, name='Update_AppraisalC_B'),
    path('allHR/<int:pk>/Update/UpdateS/', views.UpdateAppraisalS_B, name='Update_AppraisalS_B'),
    path('allHR/<int:pk>/Update/Career', views.UpdateAppraisalCareer_B, name='Update_AppraisalCareer_B'),
    path('allHR/<int:pk>/Update/', views.Update_Appraisal_B, name='Update_Appraisal_B'),


    #Checkbox User Appraisals
    path('allHR/<int:pk>/AddUserAppraisal_Indiv', views.Add_User_Appraisal_Indiv, name='Invite_Indiv_User_Appraisal'),
    path('allHR/<int:pk>/AddUserAppraisal_Dept', views.Add_User_Appraisal_Dept, name='Invite_Dept_User_Appraisal'),
    path('allHR/<int:pk>/AddUserAppraisal_Company', views.Add_User_Appraisal_Company, name='Invite_Company_User_Appraisal'),

    path('allusers/Create_Peer_Appraisal', views.Create_Peer_Appraisal, name="Create_Peer_Appraisal"),
    path('allusers/<int:pk>/Update_Peer_Appraisal', views.Update_Peer_Appraisal, name="Update_Peer_Appraisal"),
    
    # path('allusers/<int:pk>/Add_peerAppraisalQuestions', views.Add_peerAppraisalQn, name='Add_PeerAppraisalQn'),

    path('allusers/Create_OverallAppraisal/Stage1', views.create_Overall_Appraisal_Stage1, name="Create_Overall_Appraisal1"),
    path('allusers/<int:pk>/Create_OverallAppraisal/Stage3', views.create_Overall_Appraisal_Stage3, name="Create_Overall_Appraisal_Stage3"),
    path('allusers/<int:pk>/Create_OverallAppraisal/Stage4', views.create_Overall_Appraisal_Stage4, name="Create_Overall_Appraisal_Stage4"),

    path('allusers/<int:pk>/<int:mk>/<int:dk>/PersonalRecord/OverallAppraisal/Detail', views.PersonalAppraisalReport, name="Detail_PersonalRecord_OverallApp"),


    path('allusers/<int:pk>/CompanyRecord/OverallAppraisal/FAR', views.Comp_FinalAppReport, name='Comp_FAReport'),
    path('allusers/<int:pk>/CompanyRecord/ExportFAR', views.export_FinalAppraisalReport, name='export_FAReport'),

    path('allusers/<int:pk>/CompanyRecord/OverallAppraisal/FPR', views.Comp_FinalPayoutReport, name='Comp_FPReport'),
    path('allusers/<int:pk>/CompanyRecord/ExportFPR', views.export_FinalPayoutReport, name='export_FPReport'),

    path('allusers/<int:pk>/CompanyRecord/OverallAppraisal/IRR', views.Comp_IncremRecommReport, name='Comp_IRReport'),
    path('allusers/<int:pk>/CompanyRecord/ExportIRR', views.export_IncremRecommReport, name='export_IRReport'),

    path('allusers/<int:pk>/CompanyRecord/OverallAppraisal/TRR', views.Comp_TrainingRecommReport, name='Comp_TRReport'),
    path('allusers/<int:pk>/CompanyRecord/ExportTRR', views.export_TrainingRecommReport, name='export_TRReport'),

    path('allusers/<int:pk>/CompanyRecord/OverallAppraisal/CR', views.Comp_CalibrationReport, name='Comp_CPReport'),
]

EM/urls.py
from django.urls import path

from . import views

app_name = 'EM'
urlpatterns=[
    path('HR/', views.HR_EM, name = 'HR_EM'),
    path('HRM/', views.HRM_EM, name = 'HRM_EM'),

    path('HR/create_profiles/', views.Create_Profile.as_view(), name ='Create_Profile'),

    path('HR/<int:pk>/', views.Profile_View.as_view(), name ='Detail_Profile'),
    path('HR/<int:pk>/DeleteP', views.Delete_Profile.as_view(),name='Delete_Profile'),
    path('HR/<int:pk>/UpdateP', views.Update_Profile.as_view(), name ='Update_Profile')
]

denselight/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('login2.urls')),
    path('Trainings/', include ('Trainings.urls')),
    path('EM/', include('EM.urls')),
    path('Ticketing/', include('Ticketing.urls')),
    path('GnC/', include('GnC.urls')),
    path('Appraisals/', include('Appraisals.urls'))
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
document_root=settings.MEDIA_ROOT)
    

mysite/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('login2.urls')),
    path('Trainings/', include ('Trainings.urls')),
    path('EM/', include('EM.urls')),
    path('Ticketing/', include('Ticketing.urls')),
    path('GnC/', include('GnC.urls')),
    path('Appraisals/', include('Appraisals.urls'))
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
document_root=settings.MEDIA_ROOT)
    

Appraisals/templates/Appraisals/Delete_AppCat.html
<!--Inherit HTML from parent class 'utiltiypage'-->
{%extends 'utilitypage.html'%}

<!--Load static is to load static files (HTML/CSS/Js)-->
{%load static%}
<!--To inform website version of HTML-->
<!DOCTYPE html>
<!--Inform website of language of HTML-->
<html lang="en">
<!--Header-->
<head>
      <!--Meta to improve SEO-->
    <meta charset="UTF-8">
    <meta name="viewport" content="width=<device-width>, initial-scale=1.0">

    <!--HTML inheritance: overriding parent class title block(Django exclusive)-->
    <title>{%block title%}Appraisal Category Deletion{%endblock%}</title>
</head>
<body>
    {%block content%}
    <div class = "container col-6">
        <br>
        <!--HTML form, action on current page, use 'POST' method (secure)-->
        <div class = "card card-body">
            <form action="" method='POST'>
            <div class="form-group">
                    <!--Django Exclusive: CSRF token is a random, hard-to-guess string, prevent CSRF atk-->
                    {%csrf_token%}

                    <!--Things within double braces are object instances within a queryset, so in this case I am accessing object's summary-->
                    <h5>Delete appraisal category: "{{object.name}}"?</h5>

                    <div class = "row justify-content-end m-0">
                        <a class = "btn btn-danger mr-2" type = "button" href="{% url 'user_homepage'%}">Cancel</a>
                        <input type ="submit" value = "Submit">
                    </div>
                </div>
            </form>
        </div>
    </div>

    {%endblock%}
</body>

Appraisals/templates/Appraisals/Delete_OverallApp.html
<!--Inherit HTML from parent class 'utiltiypage'-->
{% load widget_tweaks %}
<!--Load static is to load static files (HTML/CSS/Js)-->
{% load static %}



<!--To inform website version of HTML-->
<!DOCTYPE html>
<!--Inform website of language of HTML-->
<html lang="en">
<!--Header-->
<head>

    <script src="js/jquery-3.4.1.min.js"></script>
    <script src="js/custom.js"></script>

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">

    <!--django bootstrap modal-->
    <link rel="stylesheet" href="{% static 'assets/css/bootstrap.css' %}">


      <!--Meta to improve SEO-->
    <meta charset="UTF-8">
    <meta name="viewport" content="width=<device-width>, initial-scale=1.0">

    <!--HTML inheritance: overriding parent class title block(Django exclusive)-->
    <title>{%block title%}Overall Appraisals Deletion{%endblock%}</title>
</head>
<body>
    {%block content%}
    <div class = "container col-6">
        <br>
        <div class = "card card-body">
            <!--HTML form, action on current page, use 'POST' method (secure)-->
            <form action="" method='POST'>
                {%csrf_token%}
                <!--<div class="modal-header">
                    <h5 class="modal-title">Delete Appraisal</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                    </button>
                </div>-->

        
                <h5>Confirm delete Appraisal: {{object.name}}?</h5>


                <!--<div class = "modal-footer">-->
                <div class = "row justify-content-end m-0">
                    <button class = "btn btn-danger mr-2"href = "{% url 'user_homepage'%}">Cancel</button>
                    <input type ="submit" class="btn btn-primary" value = "Submit">
                </div>

            </form>
        </div>
    </div>

    <script src="{% static 'assets/js/bootstrap.js' %}"x></script>
    <script src="{% static 'assets/js/jquery.js' %}"></script>
    <script src="{% static 'js/jquery.bootstrap.modal.forms.js' %}"></script>
    <!-- You can alternatively load the minified version -->
    <script src="{% static 'js/jquery.bootstrap.modal.forms.min.js' %}"></script>
    {%endblock%}
</body>

Appraisals/templates/Appraisals/Delete_RatingScale.html
<!--Inherit HTML from parent class 'utiltiypage'-->
{%extends 'utilitypage.html'%}

<!--Load static is to load static files (HTML/CSS/Js)-->
{%load static%}
<!--To inform website version of HTML-->
<!DOCTYPE html>
<!--Inform website of language of HTML-->
<html lang="en">
<!--Header-->
<head>
      <!--Meta to improve SEO-->
    <meta charset="UTF-8">
    <meta name="viewport" content="width=<device-width>, initial-scale=1.0">

    <!--HTML inheritance: overriding parent class title block(Django exclusive)-->
    <title>{%block title%}Rating Scale - Deletion{%endblock%}</title>
</head>
<body>
    {%block content%}
    <div class = "container col-6">
        <br>

        <div class = "card card-body">
            <!--HTML form, action on current page, use 'POST' method (secure)-->
            <form action="" method='POST'>
            <div class="form-group">
                    <!--Django Exclusive: CSRF token is a random, hard-to-guess string, prevent CSRF atk-->
                    {%csrf_token%}

                    <!--Things within double braces are object instances within a queryset, so in this case I am accessing object's summary-->
                    <h5>Confirm delete rating scale: "{{object.name}}"?</h5>

                    <div class = "row justify-content-end m-0">
                        <a class = "btn btn-danger mr-2" type = "button" href="{% url 'user_homepage'%}">Cancel</a>
                        <input class = "btn btn-primary" type ="submit" value = "Submit">
                    </div>
                </div>
            </form>
        </div>
    </div>

    {%endblock%}
</body>

Appraisals/templates/Appraisals/HuNetM_UpdateG.html
{%extends 'Appraisals/HuNet_UpdateG.html'%}
{%load static%}
{%block heading%}<h4 class = "heading"> Supervisor/Manager-Rating: Goals</h4>{%endblock%}

{%block bubbleurl%}
    <div id="line"></div>
    <div class = "row button-row"  style = "margin: 0">
    <a href="{% url 'Appraisals:Update_AppraisalG_M' employee_appraisal.id %}"><button type = "button" class = "btn activebtn">1</button></a>
    <a href="{% url 'Appraisals:Update_AppraisalC_M' employee_appraisal.id %}"><button type = "button" class = "btn">2</button></a>
    <a href="{% url 'Appraisals:Update_AppraisalS_M' employee_appraisal.id %}"><button type = "button" class = "btn">3</button></a>
    <a href="{% url 'Appraisals:Update_AppraisalCareer_M' employee_appraisal.id %}"><button type = "button" class = "btn">4</button></a>
    <a href="{% url 'Appraisals:Update_Appraisal_M' employee_appraisal.id %}"><button type = "button" class = "btn">5</button></a>
    </div> 
    <div class = "row button-name-row justify-content-between m-0">
        <span>Goals Rating</span>
        <span>Core Values Competencies Rating</span>
        <span>Skills Rating</span>
        <span>Career Discussion</span>
        <span>Summary</span>
    </div>
{%endblock%}

{%block rejectioncomments%}
<br>

<div class = "alert alert-warning">
    <h6 class = "alert-heading">
        HR Comments: 
    </h6>   
    <hr>
    {%if employee_appraisal.appraisalHR_rejection == 'NIL' %}
    {%else%}

    {{employee_appraisal.appraisalHR_rejection}}
    {%endif%}
</div>
{%endblock%}


Appraisals/templates/Appraisals/HuNet_Create.html
<!--Inherit HTML from parent class 'sidenav'-->
{%extends 'sidenav.html'%}

<!--Load static is to load static files (HTML/CSS/Js)-->
{%load static%}
<!--To inform website version of HTML-->
<!DOCTYPE html>
<!--Inform website of language of HTML-->
<html lang="en">
<!--Header-->
<head>
    <!--HTML inheritance: overriding parent class title block(Django exclusive)-->
    <title>{%block title%}Competencies Creation {%endblock%}</title>
</head>
<body>
    {%block content%}
    <!--HTML form, action on current page, use 'POST' method (secure)-->

    <form action= "" method = "POST">
        <div class="form-group">
            <!--Django Exclusive: CSRF token is a random, hard-to-guess string, prevent CSRF atk-->
            {%csrf_token%}
            
            <!--Generate form organised in paragraphs based on query on CreateCompetencies in GnC/views.py-->
            {{form.as_p}}
            <input type = 'submit' value = "Submit">
        </div>
    </form>
    {%endblock%}
</body>
</html>

Appraisals/templates/Appraisals/HuNet_CreateNReviewpeer.html
<!--Inherit HTML from parent class 'sidenav'-->
{%extends 'sidenav.html'%}

<!--Load static is to load static files (HTML/CSS/Js)-->
{%load static%}
<!--To inform website version of HTML-->
<!DOCTYPE html>
<!--Inform website of language of HTML-->
<html lang="en">
<!--Header-->
<head>
    <!--HTML inheritance: overriding parent class title block(Django exclusive)-->
    <title>{%block title%}Peer Appraisal Creation{%endblock%}</title>
</head>
<body>
    {%block content%}
    <!--HTML form, action on current page, use 'POST' method (secure)-->
 
    <form action= "" method = "POST">
        <div class="form-group">
            <!--Django Exclusive: CSRF token is a random, hard-to-guess string, prevent CSRF atk-->
            {%csrf_token%}
            <!--Generate form organised in paragraphs based on query on CreateCompetencies in GnC/views.py-->
            {{formset.as_p}}
            <input type = 'submit' value = "Submit">
        </div>
    </form>
    {%endblock%}
</body>
</html>

Appraisals/templates/Appraisals/HuNet_CreateOverallApp_Stage1.html

<!--Load static is to load static files (HTML/CSS/Js)-->
{%load static%}
<!--To inform website version of HTML--> 
<!DOCTYPE html>
<!--Inform website of language of HTML-->
<html lang="en">
<!--Header-->
<head>
    <!--jquery-->
    <script src="js/jquery-3.4.1.min.js"></script>
    <script src="js/custom.js"></script>

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">

    <link rel = "stylesheet" type="text/css" href = "{% static 'Appraisals/HuNet_UpdateGCS.css' %}">

    <!--font--> 
    <link href="https://fonts.googleapis.com/css2?family=Hind:wght@600&display=swap" rel="stylesheet"> <!--hind-->
    <link href="https://fonts.googleapis.com/css2?family=Open+Sans&display=swap" rel="stylesheet"> <!--open sans-->
    
    <!--HTML inheritance: overriding parent class title block(Django exclusive)-->
    <title>Create Overall Aprpaisal</title>
    <style>
        .radio-row input {
            position: absolute;
            opacity: 0;
            cursor: pointer;
        }

        .radio-row label {
            font-weight: 500;
            cursor: pointer;
            height: 50px;
            border: 1px solid #2952A4;
            color: #2952A4;
            padding: 10px;
            position: relative;
            transition: 0.3s;
            border-radius: 4px;
        }

        input[type="radio"]:checked + label {
            background-color: #2952A4;
            color: white;
        }

        input[type="radio"]:checked + label i {
            color: #2952A4;
        }

        .checkmark {
            position: absolute;
            top: 10px;
            right: 10px;
            height: 25px;
            width: 25px;
            background-color: #eee;
            border-radius: 50%;
        }

        .checkmark i {
            position: relative;
            right: -4px;
            color: #eee;
        }


</style>
</head>

<body>
    <!--HTML form, action on current page, use 'POST' method (secure)-->
    <div class = "container col-6">
        <br>
        <div class = "card">
            <div class = "card-header">
                <h2>Create Overall Appraisal</h2>
            </div>
            <div class = "card-body">
                <form action= "" method = "POST">
                    <div class="form-group">
                        <!--Django Exclusive: CSRF token is a random, hard-to-guess string, prevent CSRF atk-->
                        {%csrf_token%}
                        {%block instructions%}
                        <div class = "card card-body pb-0">
                            <ol>
                                <strong>Instructions:</strong>
                                <li>Name the Performance Appraisal Cycle</li>
                                <li>Select the Appraisal Category</li>
                                <li>Select the Employees to be included</li>
                                <li>Click "Submit"</li>
                            </ol>
                        </div>
                        <br>
                        {%endblock%}
                        <!--Generate form organised in paragraphs based on query on CreateCompetencies in GnC/views.py-->
                        {%block form%}
                        {{form.as_p}}
                        {%endblock%}

                        {%block selectemployee%}
                        <p>Select:</p>
                        
                        <div class = "row radio-row">
                            <div class = "col">
                                <input type="radio" name="employee_selection_list" id="Company" value="Company" />
                                <label for="Company" class = "col radio-option"> 
                                    <span class="checkmark"><i class="fa fa-check" aria-hidden="true"></i></span>
                                    Company
                                </label>
                            </div>
                            <div class = "col">
                                <input type="radio" name="employee_selection_list" id="Department" value="Department" />
                                <label for="Department" class = "col radio-option">
                                    <span class="checkmark"><i class="fa fa-check" aria-hidden="true"></i></span>
                                    Department
                                </label>
                            </div>
                            <div class = "col">
                                <input type="radio" name="employee_selection_list" id="Individual" value="Individual" />
                                <label for="Individual" class = "col radio-option"> 
                                    <span class="checkmark"><i class="fa fa-check" aria-hidden="true"></i></span>
                                    Individual
                                </label>
                            </div>
                        </div>
                        {%endblock%}

                        <ul class="messages">
                            {% for message in messages %}
                                <li class="{{ message.tags }}">{{ message }}</li>
                            {% endfor %}
                        </ul>

                        <div class = "row m-0 justify-content-end">
                            <a class = "btn btn-danger mr-2" type = "button" value = "Cancel" href ="{% url 'user_homepage'%}">Cancel</a>
                            <input class = "btn btn-primary" type = 'submit' value = "Submit">
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
</body>
</html>

Appraisals/templates/Appraisals/HuNet_Update.html
<!--Inherit HTML from parent class 'sidenav'-->
{%extends 'utilitypage.html'%}

<!--Load static is to load static files (HTML/CSS/Js)-->
{%load static%}
<!--To inform website version of HTML-->
<!DOCTYPE html>
<!--Inform website of language of HTML-->
<html lang="en">
<!--Header--> 
<head>
    <!--HTML inheritance: overriding parent class title block(Django exclusive)-->
    <title>{%block title%}Self Appraisal{%endblock%}</title>
</head>
<body>
    {%block content%}

    <div class = "container col-6">
        <br>
        <div class = "card card-body">
            <!--HTML form, action on current page, use 'POST' method (secure)-->
            <div class="form-group">
                <form action='' method = "POST" enctype= "multipart/form-data">
                    <!--Django Exclusive: CSRF token is a random, hard-to-guess string, prevent CSRF atk-->

                    {%csrf_token%}
                
                    {{ goals_formset.management_form }}
                        {% for form in goals_formset %}
                            {{form.as_p}}
                        {%endfor%}

                    <div class = "row justify-content-end m-0">
                        <a href = "{% url 'user_homepage'%}" class = "btn btn-danger mr-2" type = "button">Cancel</a>       
                        <input type = 'submit' value = "Submit" >
                    </div>
                </form>
            </div>
        </div>
    </div>
    {%endblock%}
</body>
</html>

Appraisals/templates/Appraisals/HuNet_Update2.html
{%extends 'utilitiespage.html'}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{%block title%}Document{%endblock%}</title>
</head>
<body>
    {%block content%}
    <form method="POST">
        {% csrf_token %}
        {% for form in forms %}
            {{ form.as_p }}
        {% endfor %}
            <input type="submit" value="Submit" />
    </form>
    {%endblock%}
</body>
</html>