EM/urls.py
from django.urls import path

from . import views

app_name = 'EM'
urlpatterns=[
    path('HR/', views.HR_EM, name = 'HR_EM'),
    path('HRM/', views.HRM_EM, name = 'HRM_EM'),

    path('HR/create_profiles/', views.Create_Profile.as_view(), name ='Create_Profile'),

    path('HR/<int:pk>/', views.Profile_View.as_view(), name ='Detail_Profile'),
    path('HR/<int:pk>/DeleteP', views.Delete_Profile.as_view(),name='Delete_Profile'),
    path('HR/<int:pk>/UpdateP', views.Update_Profile.as_view(), name ='Update_Profile')
]

GnC/urls.py
from django.urls import path

from . import views
from .views import User_GnC, Manager_GnC,  Create_Departmental_Goals, Create_Competencies, Create_Departmental_Competencies

app_name = 'GnC'
urlpatterns = [
    path('user/', views.User_GnC, name = "User_GnC"),
    path('manager/', views.Manager_GnC, name = "Manager_GnC"),
    path('HR/', views.HR_GnC, name = "HR_GnC"),
    
    path('allusers/<int:pk>/create_departmental_goals/', views.Create_Departmental_Goals.as_view(), name = "Create_Manager_Goals"),
    path('allusers/<int:pk>/create_departmental_competencies/', views.Create_Departmental_Competencies.as_view(), name="Create_Manager_Competencies"),
    path('allusers/<int:pk>/create_goals/', views.Create_Goals.as_view(), name ="Create_User_Goals1"),
    path('allusers/<int:pk>/create_competencies/', views.Create_Competencies.as_view(), name = "Create_User_Competencies"),
    path('allusers/<int:pk>/create_KPI/', views.Create_KPI.as_view(), name = "Create_User_KPIs"),
    path('allusers/<int:pk>/UserGnC/Create_GoalsCom', views.Create_Goals_Comments.as_view(), name='Create_User_Goals_Comments'),
    path('allusers/<int:pk>/UserGnC/Create_CompetenciesCom', views.Create_Competencies_Comments.as_view(), name ='Create_User_Competencies_Comments'),

    path('allusers/<int:pk>/DepartmentG', views.Departmental_Goals_View.as_view(), name="Detail_Departmental_Goals"),
    path('allusers/<int:pk>/UserG', views.Goals_View.as_view(), name = "Detail_Goals"),
    path('allusers/<int:pk>/UserC', views.Competencies_View.as_view(), name="Detail_Competencies"),
    path('allusers/<int:pk>/UserGnC', views.Department_View.as_view(), name="Detail_Users"),
    path('allusers/<int:pk>/Departments', views.HRDepartment_view.as_view(), name="Detail_Departments"),

    path('allusers/<int:pk>/DeleteG', views.Goals_Delete.as_view(), name = "Delete_User_Goals"),
    path('allusers/<int:pk>/DeleteDepartmentalG', views.Departmental_Goals_Delete.as_view(), name ="Delete_Departmental_Goals"),
    path('allusers/<int:pk>/DeleteDepartmentalC', views.Departmental_Competencies_Delete.as_view(), name="Delete_Departmental_Competencies"),
    path('allusers/<int:pk>/DeleteC', views.Competencies_Delete.as_view(), name ="Delete_User_Competencies"),
    path('allusers/<int:pk>/DeleteKPI', views.KPI_Delete.as_view(), name="Delete_User_KPI"),

    path('allusers/<int:pk>/UpdateG', views.Update_Goals_User.as_view(), name ="Update_User_Goals1"),
    path('allusers/<int:pk>/UpdateDepartmentalG', views.Update_Departmental_Goals.as_view(), name ='Update_Departmental_Goals'),
    path('allusers/<int:pk>/UpdateDepartmentalC', views.Update_Departmental_Competencies.as_view(), name='Update_Departmental_Competencies'),
    path('allusers/<int:pk>/UpdateC', views.Update_Competencies_User.as_view(), name='Update_User_Competencies'),
    path('allusers/<int:pk>/UpdateKPI', views.Update_KPI.as_view(), name ='Update_KPI'),
    path('allusers/<int:pk>/UpdateKPI_POST', views.Update_KPI_POST.as_view(), name ='Update_KPI_POST'),
    path('allusers/<int:pk>/UpdateKPI_POST1', views.Update_KPI_POST1.as_view(), name ='Update_KPI_POST1'),
    path('allusers/<int:pk>/UpdateKPI_POST2', views.Update_KPI_POST2.as_view(), name ='Update_KPI_POST2'),
    path('allusers/<int:pk>/UpdateDepartment', views.Update_Departments.as_view(), name='Update_Department'),

    path('allusers/<int:pk>/CreatetheGoals', views.createGoals, name='Create_User_Goals'),
    path('allusers/<int:pk>/<int:mk>/UpdateG', views.updateGoals, name ="Update_User_Goals"),

    path('allusers/<int:pk>/GoalsImage', views.GoalsImage, name='Goals_Image'),
    path('allusers/<int:pk>/UploadGoalsImage', views.GoalsImageUpload, name='Goals_ImageUpload'),
]


denselight/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('login2.urls')),
    path('Trainings/', include ('Trainings.urls')),
    path('EM/', include('EM.urls')),
    path('Ticketing/', include('Ticketing.urls')),
    path('GnC/', include('GnC.urls')),
    path('Appraisals/', include('Appraisals.urls'))
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
document_root=settings.MEDIA_ROOT)
    

mysite/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('login2.urls')),
    path('Trainings/', include ('Trainings.urls')),
    path('EM/', include('EM.urls')),
    path('Ticketing/', include('Ticketing.urls')),
    path('GnC/', include('GnC.urls')),
    path('Appraisals/', include('Appraisals.urls'))
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
document_root=settings.MEDIA_ROOT)
    

GnC/models.py
from django.db import models 
from datetime import datetime
from datetime import date
from Profile.models import Profile
from Profile.models import Departments
from Appraisals.models import Appraisal, Overall_Appraisal, User_Appraisal_List
from django.core.validators import MaxValueValidator, MinValueValidator
 
class goal_comment(models.Model):
    goal = models.ForeignKey('Goals', blank = False, null = False, on_delete = models.CASCADE)
    comments = models.CharField(max_length=3000, blank = False, null = True)
    created_on = models.DateTimeField(auto_now_add=True)
    created_by = models.ForeignKey(Profile, blank = False, null = True, on_delete = models.CASCADE)

    def __str__(self):
        return self.created_by.name + ": " + self.comments

class competency_comment(models.Model):
    competency = models.ForeignKey('Competencies', blank = False, null = False, on_delete = models.CASCADE)
    comments = models.CharField(max_length=3000, blank = False, null = True)
    created_on = models.DateTimeField(auto_now_add=True)
    created_by = models.ForeignKey(Profile, blank = False, null = True, on_delete = models.CASCADE)

    def __str__(self):
        return self.created_by.name + ": " + self.comments

class departmental_goal_comment(models.Model):
    departmental_goal = models.ForeignKey('Departmental_Goals', blank = False, null = False, on_delete = models.CASCADE)
    comments = models.CharField(max_length=3000, blank = False, null = True)
    created_on = models.DateTimeField(auto_now_add=True)
    created_by = models.ForeignKey(Profile, blank = False, null = True, on_delete = models.CASCADE)

    def __str__(self):
        return self.created_by.name + ": " + self.comments

class departmental_competencies_comment(models.Model):
    departmental_competencies = models.ForeignKey('Departmental_Competencies', blank = False, null = False, on_delete = models.CASCADE)
    comments = models.CharField(max_length=3000, blank = False, null = True)
    created_on = models.DateTimeField(auto_now_add=True)
    created_by = models.ForeignKey(Profile, blank = False, null = True, on_delete = models.CASCADE)

    def __str__(self):
        return self.created_by.name + ": " + self.comments

class KPI(models.Model):
    PROGRESS_CHOICES =(
        ('Working', 'Working'),
        ('Completed', 'Completed')
    )
    goal = models.ForeignKey('Goals', on_delete=models.CASCADE)
    description = models.CharField(max_length= 150)
    due = models.DateField(blank = True, null = True)
    date_created = models.DateField(null = True, default=date.today)
    progress = models.CharField(max_length = 20, blank = False, null = False, choices = PROGRESS_CHOICES, default = 'Working')

    def __str__(self):
        return self.description


class goal_category(models.Model):
    name = models.CharField (max_length = 70, blank=False, null = False)

    def __str__(self):
        return self.name

class Goals(models.Model):
    RATING_CHOICES = [
        (1, '1 - Major Improvement Needed'),
        (2, '2 - Needs Improvement'),
        (3, '3 - Meets Expectations'),
        (4, '4 - Exceeds Expectations'),
        (5, '5 - Far Exceed Expectations')
    ]
    
    TRACKING_CHOICES = [
        ('null', 'null'),
        ('On Track', 'On Track'),
        ('Not On Track', 'Not On Track')
    ]
    appraisal = models.ForeignKey(User_Appraisal_List, blank = False, null = True, on_delete=models.SET_NULL)
    employee = models.ForeignKey(Profile, blank = False, null = True, on_delete=models.SET_NULL)
    summary = models.CharField(max_length=70, blank=False, null = False)
    goal_category = models.ForeignKey(goal_category, blank = False, null=True, on_delete = models.CASCADE)
    description = models.CharField(max_length=200, blank = True, null = True)
    due = models.DateField()
    weightage = models.IntegerField(validators=[MinValueValidator(1), MaxValueValidator(100)], blank = False, null = False)
    metrics_Used = models.CharField(max_length = 100, blank=False, null=False, default='NIL')

    MID_user_comments = models.CharField(max_length = 2000, blank = False, null = False, default='NIL')
    MID_manager_comments=models.CharField(max_length= 2000, blank = False, null = False, default='NIL')
    
    user_rating = models.IntegerField(choices = RATING_CHOICES, blank = False, null = False, default = 1)
    manager_rating = models.IntegerField(choices = RATING_CHOICES, blank = False, null = False, default = 1)
    board_rating = models.IntegerField(choices = RATING_CHOICES, blank = False, null = False, default = 1)

    user_comments = models.CharField(max_length = 2000, blank = False, null = False, default='NIL')
    manager_comments=models.CharField(max_length= 2000, blank = False, null = False, default='NIL')
    board_comments=models.CharField(max_length= 2000, blank = False, null = False, default='NIL')
    tracking_status = models.CharField(max_length=50, blank = False, null = True, default = 'null', choices=TRACKING_CHOICES)
    metrics_evidence = models.ImageField(blank = True, null = True)

    def __str__(self):
        return self.summary

    def get_kpi_filtered_completed(self):
        return self.kpi_set.filter(progress='Completed')
    
    def get_kpi_percentage(self):
        total = self.kpi_set.all().count()
        cnt = self.kpi_set.filter(progress='Completed').count()
        if total <= 0:
            return -1
        elif total>=cnt:
            perc = int(cnt * 100 / total)
            return perc
        else:
            return 0

class competency_category(models.Model):
    name = models.CharField(max_length = 1000, blank = True, null = True)
    description = models.CharField(max_length = 1000, blank = False, null = False)

    def __str__(self):
        return "{} - {}".format(self.name, self.description)

class Competencies(models.Model):
    RATING_CHOICES = [
        (1, '1 - Major Improvement Needed'),
        (2, '2 - Needs Improvement'),
        (3, '3 - Meets Expectations'),
        (4, '4 - Exceeds Expectations'),
        (5, '5 - Far Exceed Expectations')
    ]

    appraisal = models.ForeignKey(User_Appraisal_List, blank = False, null = True, on_delete=models.SET_NULL)
    employee = models.ForeignKey(Profile, blank = False, null = True, on_delete = models.SET_NULL)
    competency_category = models.ForeignKey(competency_category, blank = False, null = True, on_delete=models.CASCADE)
    summary = models.CharField(max_length = 150, blank = False, null = False)
    description = models.CharField(max_length=1000, blank= True, null = True)
    weightage = models.IntegerField(validators=[MinValueValidator(1), MaxValueValidator(100)], blank = False, null = False)

    user_rating = models.IntegerField(choices = RATING_CHOICES, blank = False, null = False, default = 1)
    manager_rating = models.IntegerField(choices = RATING_CHOICES, blank = False, null = False, default = 1)
    board_rating = models.IntegerField(choices = RATING_CHOICES, blank = False, null = False, default = 1)

    user_comments = models.CharField(max_length = 2000, blank = False, null = False, default='NIL')
    manager_comments=models.CharField(max_length=2000, blank = False, null = False, default='NIL')
    board_comments=models.CharField(max_length= 2000, blank = False, null = False, default='NIL')

    def __str__(self):
        return self.summary

class Departmental_Goals(models.Model):
    manager = models.ForeignKey(Profile, blank = False, null = True, on_delete=models.SET_NULL)
    appraisal = models.ForeignKey(Overall_Appraisal, blank = False, null = True, on_delete=models.SET_NULL)
    department = models.ForeignKey(Departments, null=True, on_delete=models.CASCADE)
    summary = models.CharField(max_length=70, blank=False, null = False)
    goal_category = models.ForeignKey(goal_category, blank = False, null = True, on_delete=models.CASCADE)
    description = models.CharField(max_length=200, blank = True, null = True)
    due = models.DateField()

    def __str__(self):
        return self.summary

class Departmental_Competencies(models.Model):
    manager = models.ForeignKey(Profile, blank = False, null = True, on_delete=models.SET_NULL)
    appraisal = models.ForeignKey(Overall_Appraisal, blank = False, null = True, on_delete=models.SET_NULL)
    department = models.ForeignKey(Departments, null=True, on_delete=models.CASCADE)
    summary = models.CharField(max_length=70, blank=False, null = False)
    competency_category = models.ForeignKey(goal_category, blank = False, null = True, on_delete=models.CASCADE)
    description = models.CharField(max_length=200, blank = True, null = True)

    def __str__(self):
        return self.summary


    

GnC/templates/GnC/HuNet_DetailGoals.html
<!--Inherit HTML from parent class 'utiltiypage'-->
{%extends 'homepage.html'%}
<!--Load static is to load static files (HTML/CSS/Js)-->
{%load static%}
<!--To inform website version of HTML-->
<!DOCTYPE html>
<!--Inform website of language of HTML-->
<html lang="en">
<!--Header-->
<head>
      <!--Meta to improve SEO-->
    <meta charset="UTF-8"> 
    <meta name="viewport" content="width=<device-width>, initial-scale=1.0">

    <!--HTML inheritance: overriding parent class title block(Django exclusive)-->
    <title>{%block title%}Goal Detail{%endblock%}</title>

    {%block script1%}
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <link rel = "stylesheet" type="text/css" href = "{% static 'GnC/HuNet_DetailGoals.css' %}">
    {%endblock%}
</head>
<body>
    <!--HTML inheritance: overriding parent class content block(Django exclusive)-->
    {%block content%}
    <div class = "container">
    
        <!--Things within double braces are object instances within a queryset, so in this case I am accessing goal's employee-->
        <!-- original layout
        <p>Name: {{object.employee.name}}</p>
        <p>Appraisal ID:</p>
        <p>Goal Due: {{object.due}}</p>
        {%with KPI_counter=object.kpi_set.all%}<p> Number of KPIs: {{KPI_counter.count}}</p>{%endwith%}
        -->

        <br>
        
        <div class = "row">
            <div class = "col-12">
                <div class = "card-deck d-flex justify-content-around">
                    <div class = "card shadow-sm">
                        <div class = "card-header">
                            Name:
                        </div>

                        <div class = "card-body">
                            {{object.employee.name}}
                        </div>
                    </div>

                    <div class = "card shadow-sm">
                        <div class = "card-header">
                            Appraisal ID:
                        </div>

                        <div class = "card-body">
                            NIL
                        </div>
                    </div>
                    
                    <div class = "card shadow-sm">
                        <div class = "card-header">
                            Goal Due: 
                        </div>

                        <div class = "card-body">
                            {{object.due}}
                        </div>
                    </div>

                    {%with KPI_counter=object.kpi_set.all%}
                    <div class = "card shadow-sm"> 
                        <div class = "card-header">
                            Number of KPIs: 
                        </div>

                        <div class = "card-body">
                            {{KPI_counter.count}}
                        </div>
                    </div>
                    {%endwith%}
                </div>
            </div>
        </div>

        <br>

        <div class = "row justify-content-center">
            <div class = "col-12">
                <div class = "card shadow-sm">
                    <table class = "table mb-0 pb-0">
                        <thead>
                            <tr>
                                <th scope="col">ID </th>
                                <th scope="col">Summary</th>
                                <th scope="col">Description</th>
                                <th scope="col">Due</th>
                                <th scope="col">Date Created</th>
                                <th scope="col" colspan="2">Actions</th>
                            </tr>
                        </thead>
                        <tbody>
                            <tr>
                                <td>Goal {{object.id}}</td>
                                <td>{{object.summary}}</td>
                                <td>{{object.description}}</td>
                                <td>NA</td>
                                <td>NA</td>
                                <td></td>
                                <td></td>
                            </tr>   
                            {% for kpi in object.kpi_set.all %}
                            <tr>
                                <td>KPI {{kpi.id}}</td>
                                <td colspan="2">{{kpi.description}}</td>
                                <td>{{kpi.due}}</td>
                                <td>{{kpi.date_created}}</td>
                                {% if kpi.goal.status != 'Approved'%}
                                <td><a href="{% url 'GnC:Update_KPI' kpi.id %}">Update</a></td>
                                <td><a href="{% url 'GnC:Delete_User_KPI' kpi.id %}">Delete</a></td>
                                {%else%}
                                <td><a href="{%url 'GnC:Update_KPI_POST' kpi.id %}">Update</a></td>
                                <td></td>
                                
                                {%endif%}
                            </tr>
                            {% endfor %}
                        </tbody>
                    </table>
                </div>
            </div>
        </div>


        <h4>Comments</h4>
        <a href="{%url 'GnC:Create_User_Goals_Comments' object.id%}">Create Comments</a>
        <table>
            <thead>
                <tr>
                    <th> </th>
                    <th> </th>
                    <th> </th>
                    <th> </th>
                    <th> </th>
                    <th> </th>
                    <th> </th>
                </tr>
            </thead>

            <tbody>
                {%for comments in object.goal_comment_set.all|dictsort:"created_on"%}
                {% if comments.created_by == comments.goal.employee %}
                <tr>
                    <td rowspan="2" colspan="4">{{comments.created_by.name}}: {{comments.comments}}</td>
                    <td colspan="3"></td>
                </tr>
                <tr>
                    <td>{{comments.created_on}}</td>
                    <td colspan="2"></td>
                </tr>

                {% else %}
                <tr>
                    <td colspan="3"></td>
                    <td rowspan="2" colspan="4">{{comments.created_by.name}}: {{comments.comments}}</td>
                </tr>
                <tr>
                    <td colspan="2"></td>
                    <td>{{comments.created_on}}</td>
                </tr>
                {%endif%}
                {%endfor%}
            </tbody>
        </table>

    </div>
    {%endblock%}
</body>

GnC/templates/GnC/XHuNetM_GnC.html
<!--Inherit HTML from parent class 'utiltiypage'-->
{%extends 'utilitypage.html'%}

<!--Load static is to load static files (HTML/CSS/Js)-->
{% load static %}
<head>
    <!--HTML inheritance: overriding parent class title block(Django exclusive)-->
    <title>{%block title%}Goals and Competencies{%endblock%}</title>
</head>
<body>
    <!--Page wrapper bg-->
    <div class = "wrapper">
        <!--HTML inheritance: overriding parent class content block(Django exclusive)-->
        {%block content%}

        <!--User vs Department tab-->
        <section class="main">
            <!--Tab section within goals-->
            <div class="tab_main">
                <button class="tablinks" onclick="openCity(event, 'self', 'General_Scope', 'tablinks')">User</button>
                <button class="tablinks" onclick="openCity(event, 'department', 'General_Scope', 'tablinks')">Department</button>
            </div>

            <!--User's Personal vs user's departmental goal tab-->
            <div class='General_Scope' id="self">
                <section class = "Goals">
                    <div class="tab_self">
                        <button class="tablinks1" onclick="openCity(event, 'goals_team', 'tabcontent_goals', 'tablinks1')">Departmental Goals and Competencies</button>
                        <button class="tablinks1" onclick="openCity(event, 'goals_self', 'tabcontent_goals', 'tablinks1')">Personal Goals and Competencies</button>
                    </div>

                    <!--**Dynamic routing to 'GnC/CreateDepartmentalGoals.html' template -->
                    <a href="{%url 'GnC:Create_Manager_Competencies'%}">Add Departmental Competencies</a>
                    <a href="{%url 'GnC:Create_Manager_Goals' %}">Add Departmental Goals</a>
                    <!--**Dynamic routing to 'GnC/CreateGoals.html' template -->
                    <a href="{%url 'GnC:Create_User_Goals' %}">Add User Goals</a>
                    <!--**Dynamic routing to 'GnC/CreateCompetencies.html' template -->
                    <a href="{% url 'GnC:Create_User_Competencies' %}">Add Competencies</a>

                    <!--Departmental goal table-->
                    <div id="goals_team" class="tabcontent_goals">
                        <table>
                            <thead>
                                <tr>
                                    <th scope="col">Department</th>
                                    <th scope="col">Description</th>
                                    <th scope="col">Category</th>
                                    <th scope="col">Due date</th>
                                    <th scope="col" colspan=3>Progress</th>
                                </tr>
                            </thead>
                            <tbody>
                                {%for goals in departmental_goals_list%}
                                <tr>
                                    <td>{{goals.manager.name}}</td>
                                    <td>{{goals.summary}}</td>
                                    <td>{{goals.goal_category.name}}</td>
                                    <td>{{goals.due}}</td>
                                    <td>50%</td>
                                    <td><a href="{%url 'GnC:Update_Departmental_Goals' goals.id %}">+</a></td>
                                    <td><a href="{%url 'GnC:Delete_Departmental_Goals' goals.id %}">-</a></td>
                                    <td><a href ="{% url 'GnC:Detail_Departmental_Goals' goals.id %}">Details</a></td>
                                </tr>
                                {%endfor%}
                            </tbody>
                        </table>

                        <!--Competency table (no tabs)-->
                        <table>
                            <thead>
                                <tr>
                                    <th scope="col">Department</th>
                                    <th scope="col">Competencies</th>
                                    <th scope="col">Category</th>
                                    <th scope="col">Due date</th>
                                    <th scope="col" colspan="2">Action</th>
                                </tr>
                            </thead>

                            <tbody>
                                {%for competencies in departmental_competencies_list%}
                                <tr>
                                    <td>{{competencies.department}}</td>
                                    <td>{{competencies.summary}}</td>
                                    <td>{{competencies.competency_category}}</td>
                                    <td><a href = "{% url 'GnC:Detail_Competencies' competencies.id %}">Details</a></td>
                                </tr>
                                {%endfor%}
                            </tbody>
                        </table>
                    </div>

                    <!--User goal table-->
                    <div id="goals_self" class="tabcontent_goals">
                        <table>
                            <thead>
                                <tr>
                                    <th scope="col">Description</th>
                                    <th scope="col">Category</th>
                                    <th scope="col">Due date</th>
                                    <th scope="col">Progress</th>
                                    <th scope="col" colspan="4">Action</th>
                                </tr>
                            </thead>

                            <tbody>
                                {%for goals in goals_list%}
                                <tr>
                                    <td>{{goals.summary}}</td>
                                    <td>{{goals.goal_category.name}}</td>
                                    <td>{{goals.due}}</td>
                                    <td>75%</td>
                                    <td><a href="{%url 'GnC:Create_User_KPIs' goals.id %}">KPI</a></td>
                                    <td><a href="{% url 'GnC:Update_User_Goals' goals.id %}">+</a></td>
                                    <td><a href = "{% url 'GnC:Delete_User_Goals' goals.id %}">-</a></td>
                                    <td><a href = "{% url 'GnC:Detail_Goals' goals.id %}">Details</a></td>
                                </tr>
                                {%endfor%}
                            </tbody>
                        </table>

                        <!--Competency table (no tabs)-->
                        <table>
                            <tr>
                                <th scope="col">Competencies</th>
                                <th scope="col">Category</th>
                                <th scope="col">Due date</th>
                                <th scope="col" colspan="2">Action</th>
                            </tr>

                            {%for competencies in competencies_list%}
                            <tr>
                                <td>{{competencies.summary}}</td>
                                <td>{{competencies.competency_category.name}}</td>
                                <td>{{competencies.due}}</td>
                                <td><a href="{% url 'GnC:Update_Competencies' competencies.id %}">+</a></td>
                                <td><a href = "{% url 'GnC:Delete_User_Competencies' competencies.id %}">-</a></td>
                                <td><a href = "{% url 'GnC:Detail_Competencies' competencies.id %}">Details</a></td>
                            </tr>
                            {%endfor%}
                        </table>
                    </div>
                </section>

            </div>

            <hr><!--Horizontal rule-->

            <!--Employee Departmental Tab & table-->
            <div class="General_Scope" id="department">
                <section class = "Goals_search team_view">

                    <!--Search form with submit button-->
                    <form class="example">
                        <input type="text" placeholder="Search.." name="search">
                        <button type="submit"><i class="fa fa-search">Submit</i></button>
                    </form>

                    <table>
                        <thead>
                            <tr>
                                <th scope="col">Name</th>
                                <th 
                                scope="col">Department</th>
                                <th scope="col">Email</th>
                                <th scope="col">Goal count</th>
                                <th scope="col">Competencies count</th>
                                <th scope="col">Status</th>
                                <th scope="col">Action</th>
                            </tr>
                        </thead>

                        <tbody>
                            {%for profile in department_detailed_view%}
                            <tr>
                                <td>{{profile.name}}</td>
                                <td>{%for x in profile.department.all%}:{{x.name}}: {%endfor%}</td>
                                <td>{{profile.email}}</td>
                                <td>{{profile.goals_set.all.count}}</td>
                                <td>{%with competency_count=profile.competencies_set.all%}{{competency_count|length}}{%endwith%}</td>
                                <td>Locked</td>
                                <td><a href = "{% url 'GnC:Detail_Users' profile.id %}">Details</a></td>
                            </tr>
                            {%endfor%}
                        </tbody>
                    </table>
                </section>
            </div>

        </section>
        {%endblock%}
    </div>
</body>