EM/urls.py
from django.urls import path

from . import views

app_name = 'EM'
urlpatterns=[
    path('HR/', views.HR_EM, name = 'HR_EM'),
    path('HRM/', views.HRM_EM, name = 'HRM_EM'),

    path('HR/create_profiles/', views.Create_Profile.as_view(), name ='Create_Profile'),

    path('HR/<int:pk>/', views.Profile_View.as_view(), name ='Detail_Profile'),
    path('HR/<int:pk>/DeleteP', views.Delete_Profile.as_view(),name='Delete_Profile'),
    path('HR/<int:pk>/UpdateP', views.Update_Profile.as_view(), name ='Update_Profile')
]

denselight/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('login2.urls')),
    path('Trainings/', include ('Trainings.urls')),
    path('EM/', include('EM.urls')),
    path('Ticketing/', include('Ticketing.urls')),
    path('GnC/', include('GnC.urls')),
    path('Appraisals/', include('Appraisals.urls'))
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
document_root=settings.MEDIA_ROOT)
    

mysite/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('login2.urls')),
    path('Trainings/', include ('Trainings.urls')),
    path('EM/', include('EM.urls')),
    path('Ticketing/', include('Ticketing.urls')),
    path('GnC/', include('GnC.urls')),
    path('Appraisals/', include('Appraisals.urls'))
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
document_root=settings.MEDIA_ROOT)
    

EM/models.py
from django.db import models

# Create your models here.

EM/views.py
from .decorators import allowed_users, redirect_users
from Profile.models import Profile, Departments

from django.shortcuts import render, get_object_or_404
from django.urls import reverse_lazy, reverse
from django.contrib.auth.models import Group, User
from django.views.generic.edit import CreateView, UpdateView 
from django.contrib.auth.models import auth, Group, User
from django.contrib.auth.decorators import login_required
from django.views.generic import DetailView, DeleteView
# Create your views here.

@login_required(login_url = 'login')
@redirect_users
@allowed_users(allowed_roles=['Employee', 'Manager', 'HR', 'HR Manager'])
def HR_EM(request):
    user_department= Departments.objects.get(name = 'HR')
    Profile_database = Profile.objects.exclude(department = user_department)

    context ={
        "profile_list": Profile_database
    }
    return render(request, 'EM/HuNet_HRem.html', context)

@login_required(login_url = 'login')
@allowed_users(allowed_roles=['HR Manager'])
def HRM_EM(request):
    Profile_database = Profile.objects.all()

    context ={
        "profile_list": Profile_database
    }
    return render(request, 'EM/HuNet_HRem.html', context)
    
class Create_Profile(CreateView):
    model = Profile
    fields = ['user', 'name', 'employee_ID', 'email', 'department', 'gender', 'address_1', 'address_2', 'marital_Status', 'date_Of_Passport_Expiry', 'citizenship_Status', 'date_Of_Hire', 'job_Title', 'employment_Type', 'first_Reporting_Manager', 'second_Reporting_Manager', 'division_Centre', 'qualification_Attained', 'skills', 'phone']
    success_url = reverse_lazy('EM:HR_EM')
    template_name = 'EM/HuNet_CreateProfile.html'

    def form_valid(self, form):
        print(form.cleaned_data)
        super(Create_Profile,self).form_valid(form)


class Update_Profile(UpdateView):
    model = Profile
    fields = ['user', 'name', 'employee_ID', 'email', 'department', 'gender', 'address_1', 'address_2', 'marital_Status', 'date_Of_Passport_Expiry', 'citizenship_Status', 'date_Of_Hire', 'job_Title', 'employment_Type', 'first_Reporting_Manager', 'second_Reporting_Manager', 'division_Centre', 'qualification_Attained', 'skills', 'phone']
    template_name = 'EM/HuNet_CreateProfile.html'
    success_url = reverse_lazy('EM:HR_EM')

    def form_valid(self, form):
        print(form.cleaned_data)
        return super(Update_Profile,self).form_valid(form)

class Delete_Profile(DeleteView):
    template_name='EM/HuNet_DeleteProfile.html'
    success_url = reverse_lazy('EM:HR_EM')

    def get_object(self):
        id = self.kwargs.get("pk")
        return get_object_or_404(Profile, id=id)

class Profile_View(DetailView):
    template_name = 'EM/HuNet_DetailProfile.html'
    queryset = Profile.objects.all()

    def get_object(self):
        if self.request.user.is_authenticated:
            id = self.kwargs.get("pk")
            return get_object_or_404(Profile, id=id)
        else:
            return Profile.objects.none()


EM/templates/EM/HuNet_CreateProfile.html
<!--Inherit HTML from parent class 'sidenav'-->
{%extends 'sidenav.html'%}

<!--Load static is to load static files (HTML/CSS/Js)-->
{%load static%}
<head>
    <!--HTML inheritance: overriding parent class title block(Django exclusive)-->
    <title>{%block title%}Profile Creation {%endblock%}</title>
</head>
<body>

    {%block content%}
    <!--HTML form, action on current page, use 'POST' method (secure)-->
    <form action= "" method = "POST">
        <!--Django Exclusive: CSRF token is a random, hard-to-guess string, prevent CSRF atk-->
        {%csrf_token%}

        <!--Generate form organised in paragraphs based on query on CreateProfile in GnC/views.py-->
        {{form.as_p}}
        <input type = 'submit' value = "Create Profile">
    </form>
    {%endblock%}
</body>
</html>

EM/templates/EM/HuNet_DeleteProfile.html
<!--Inherit HTML from parent class 'utiltiypage'-->
{%extends 'utilitypage.html'%}

<!--Load static is to load static files (HTML/CSS/Js)-->
{%load static%}

<head>
    <!--HTML inheritance: overriding parent class title block(Django exclusive)-->
    <title>{%block title%}Delete Profile{%endblock%}</title>
</head>
<body>
    {%block content%}
    <!--HTML form, action on current page, use 'POST' method (secure)-->
    <form action="" method = "POST">
        <p>Would you like to delete {{object.name}}'s profile?</p>
        <!--HTML form, submit button-->
        <input type="submit" value="Confirm"> <a href="../">Cancel</a>
    </form>
    {%endblock%}
</body>

EM/templates/EM/HuNet_DetailProfile.html
<!--Inherit HTML from parent class 'utiltiypage'-->
{%extends 'utilitypage.html'%}
<head>
    <!--HTML inheritance: overriding parent class title block(Django exclusive)-->
    {%block title%}Employee Profile{%endblock%}
</head>
<body>
    {%block content%}
    <!--**Dynamic routing to 'EM:Create_Profile' template (Create and Update share same html)-->
    <a href="{%url 'EM:Update_Profile' object.id%}">Update Profile</a>
    <!--**Dynamic routing to 'EM/DeleteProfile.html' template -->
    <a href="{%url 'EM:Delete_Profile' object.id%}">Delete Profile</a>

    <!--Things within double braces are object instances within a queryset, so in this case I am accessing object's employee name-->
    <h3>Personal Particulars</h3>    
    <!--Profile name-->
    <p> name: {{object.name}}</p>
    <!--Profile Employee ID-->
    <p> ID: {{object.Employee_ID}}</p>
    <!--Profile email-->
    <p> email: {{object.email}}</p>
    <!--Profile Gender-->
    <p> gender: {{object.gender}}</p>
    <!--Profile Contact-->
    <p> contact: {{object.phone}}</p>

    <h3>Work-related</h3>
    <!--Profile Employment type-->
    <p>Position: {{object.employment_Type}} {{object.job_Title}}</p>
    <!--Profile departments-->
    {% for departments in object.department.all%}
    <p>Department: {{departments.name}}</p>
    {%endfor%}
    <!--Profile Manager1-->
    <p>1st Reporting Manager: {{object.first_Reporting_Manager}}</p>
    <!--Profile Manager2-->
    <p>2nd Reporting Manager: {{object.second_Reporting_Manager}}</p>
    <!--Profile Division Centre-->
    <p>Division Centre: {{object.division_Centre}}</p>
    <!--Profile Date of hire-->
    <p>Date-Of-Hire: {{object.date_Of_Hire}}</p>


    <h3>Secondary information</h3>
    <!--Profile address1-->
    <p>Address 1: {{object.address_1}}</p>
    <!--Profile address2-->
    <p>Address 2: {{object.address_2}}</p>
    <!--Profile Marital Status-->
    <p>Marital Status: {{object.marital_status}}</p>
    <!--Profile Passport expiry-->
    <p>Date of Passport Expiry: {{object.date_Of_Passport_Expiry}}</p>
    <!--Profile Citizenry-->
    <p>Citizenship Status: {{object.citizenship_Status}}</p>
    
    
    <h3>Skills</h3>
    <!--Profile Qualifications-->
    <p>Qualifications: {% for qualifications in object.qualification_Attained.all%}{{qualifications.name}},{%endfor%}</p>
    <!--Profile Skills-->
    <p>Skills: {% for skills in object.skills.all%}{{object.skills.all}},{%endfor%}</p>
    
    <h3>User</h3>
    <!--Profile user username-->
    <p>Username: {{object.user.username}}</p>
    <!--Profile user password-->
    <p>Password: {{object.user.password}}</p>
    <!--Profile user email-->
    <p>Email: {{object.user.email}}</p>
    {%endblock%}
</body>

EM/templates/EM/HuNet_HRMem.html
<!--Difference between this html and 'HuNET_HRem.html' are the querysets. The one in HRem excludes HR members themselves-->
<!--Inherit HTML from parent class 'utiltiypage'-->
{%extends 'utilitypage.html'%}

<head>
    <!--HTML inheritance: overriding parent class title block(Django exclusive)-->
    <title>{%block title%} Employee Management {%endblock%}</title>
</head>

<body>
    <!--HTML inheritance: overriding parent class content block(Django exclusive)-->
    {%block content%}
        <section>
            <!--**Dynamic routing to 'EM/CreateProfile.html' template -->
            <a href="{%url 'EM:Create_Profile' %}">Add Profile</a>
            <table>
                <!--Table for employee management-->
                <thead>
                    <th scope = "col">Name </th>
                    <th scope = "col">Dept </th>
                    <th scope = "col">Position </th>
                    <th scope = "col">1st Approving Manager </th>
                    <th scope = "col">Date of Hire </th>
                    <th scope = "col" colspan = "3">Action </th>
                </thead>
                <tbody>
                    {% for profile in profile_list%}
                    <tr>
                        <!--Employee name-->
                        <td>{{profile.name}}</td>
                         <!--Employee department--> 
                        <td>{%for department in profile.department.all%}    <ul><li>{{department.name}}</li></ul>{%endfor%}</td>
                        <!--Employee job title-->
                        <td>{{profile.job_Title}}</td> 
                        <!--Employee reporting manager-->
                        <td>{{profile.first_Reporting_Manager}}</td>
                        <!--Employee date of hire--> 
                        <td>{{profile.date_Of_Hire}}</td>
                        <!--**Dynamic routing to 'EM/CreateProfile' template (Update and Create profile share same html)-->     
                        <td><a href="{% url 'EM:Update_Profile' profile.id %}">+</a></td>
                        <!--**Dynamic routing to 'EM/CreateProfile.html' template-->  
                        <td><a href="{% url 'EM:Delete_Profile' profile.id %}">-</a></td>
                        <!--**Dynamic routing to 'EM/DetailProfile.html' template-->  
                        <td><a href="{% url 'EM:Detail_Profile' profile.id %}">Detail</a></td>               
                    </tr>
                    {%endfor%}
                </tbody>
            </table>
        </section>
    {%endblock%}
</body>

EM/templates/EM/HuNet_HRem.html
<!--Inherit HTML from parent class 'utiltiypage'-->
{%extends 'utilitypage.html'%}

<head>
    <!--HTML inheritance: overriding parent class title block(Django exclusive)-->
    <title>{%block title%} Employee Management {%endblock%}</title>
</head>

<body>
    <!--HTML inheritance: overriding parent class content block(Django exclusive)-->
    {%block content%}
        <section>
            <!--**Dynamic routing to 'EM/CreateProfile.html' template -->
            <a href="{%url 'EM:Create_Profile' %}">Add Profile</a>
            <table>
                <!--Table for employee management-->
                <thead>
                    <th scope = "col">Name </th>
                    <th scope = "col">Dept </th>
                    <th scope = "col">Position </th>
                    <th scope = "col">1st Approving Manager </th>
                    <th scope = "col">Date of Hire </th>
                    <th scope = "col" colspan = "3">Action </th>
                </thead>
                <tbody>
                    {% for profile in profile_list%}
                    <tr>
                        <!--Employee name-->
                        <td>{{profile.name}}</td>
                        <!--Employee department--> 
                        <td>{%for department in profile.department.all%}    <ul><li>{{department.name}}</li></ul>{%endfor%}</td>
                        <!--Employee job title-->
                        <td>{{profile.job_Title}}</td>
                        <!--Employee reporting manager--> 
                        <td>{{profile.first_Reporting_Manager}}</td> 
                        <!--Employee date of hire-->
                        <td>{{profile.date_Of_Hire}}</td> 
                        <!--**Dynamic routing to 'EM/CreateProfile' template (Update and Create profile share same html)-->  
                        <td><a href="{% url 'EM:Update_Profile' profile.id %}">+</a></td>
                        <!--**Dynamic routing to 'EM/CreateProfile.html' template-->  
                        <td><a href="{% url 'EM:Delete_Profile' profile.id %}">-</a></td>
                        <!--**Dynamic routing to 'EM/DetailProfile.html' template-->  
                        <td><a href="{% url 'EM:Detail_Profile' profile.id %}">Detail</a></td>               
                    </tr>
                    {%endfor%}
                </tbody>
            </table>
        </section>
    {%endblock%}
</body>