EM/urls.py
from django.urls import path

from . import views

app_name = 'EM'
urlpatterns=[
    path('HR/', views.HR_EM, name = 'HR_EM'),
    path('HRM/', views.HRM_EM, name = 'HRM_EM'),

    path('HR/create_profiles/', views.Create_Profile.as_view(), name ='Create_Profile'),

    path('HR/<int:pk>/', views.Profile_View.as_view(), name ='Detail_Profile'),
    path('HR/<int:pk>/DeleteP', views.Delete_Profile.as_view(),name='Delete_Profile'),
    path('HR/<int:pk>/UpdateP', views.Update_Profile.as_view(), name ='Update_Profile')
]

Ticketing/urls.py
from . import views
from django.urls import path

app_name = 'Ticketing'
urlpatterns=[
    path('employee/', views.User_Ticketing, name ='User_Ticket'),
    path('HRd/', views.HR_Ticketing, name ='HR_Ticket'),

    path('allusers/CreateTicket', views.Create_Ticketing.as_view(), name='Create_User_Ticket'),
    path('allusers/CreateComments', views.Create_Comments.as_view(), name='Create_User_Comment'),

    path('allusers/<int:pk>', views.Detail_Ticket.as_view(), name='Detail_Ticket'),
    path('allusers/<int:pk>/DeleteT', views.Delete_Ticket.as_view(),name='Delete_Ticket'),
    path('allusers/<int:pk>/DeleteC', views.Delete_Comments.as_view(), name='Delete_Comment'),

    path('allusers/<int:pk>/UpdateT', views.Update_Ticketing.as_view(), name='Update_Ticket'),
    path('allusers/<int:pk>/UpdateC', views.Update_Comments.as_view(), name='Update_Comment')
]

denselight/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('login2.urls')),
    path('Trainings/', include ('Trainings.urls')),
    path('EM/', include('EM.urls')),
    path('Ticketing/', include('Ticketing.urls')),
    path('GnC/', include('GnC.urls')),
    path('Appraisals/', include('Appraisals.urls'))
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
document_root=settings.MEDIA_ROOT)
    

mysite/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('login2.urls')),
    path('Trainings/', include ('Trainings.urls')),
    path('EM/', include('EM.urls')),
    path('Ticketing/', include('Ticketing.urls')),
    path('GnC/', include('GnC.urls')),
    path('Appraisals/', include('Appraisals.urls'))
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
document_root=settings.MEDIA_ROOT)
    

Ticketing/models.py
from django.db import models
from Profile.models import Profile

class Ticket_Comments(models.Model):
    ticket= models.ForeignKey('Ticket', null = True, blank = False, on_delete=models.CASCADE)
    user= models.ForeignKey(Profile, null = False, blank = False, on_delete=models.CASCADE)
    comment = models.CharField(max_length=500, blank = False, null = False)
    created_on = models.DateTimeField(auto_now_add = True)

    def __str__(self):
        return 'Comment: {} by {}'.format(self.comment, self.user.name)


class Ticket(models.Model):
    CATEGORY_CHOICES=(
        ('Profile', 'PROFILE'),
        ('Employee Management', 'EMPLOYEE MANAGEMENT'),
        ('Goals and Competencies', 'GOALS AND COMPETENCIES'),
        ('Appraisals', 'APPRAISALS'),
        ('Trainings', 'TRAININGS'),
        ('Reports', 'REPORTS'),
        ('Ticketing', 'TICKETING'),
        ('Guide', 'GUIDE'),
        ('Careers', 'CAREERS'),
        ('Others', 'OTHERS')
    )

    STATUS_CHOICE=(
        ('Pending', 'PENDING'),
        ('Working', 'WORKING'),
        ('Awaiting Reply', 'AWAITING REPLY'),
        ('Solved', 'SOLVED')
    )
    category=models.CharField(max_length = 30, choices = CATEGORY_CHOICES, blank = False, null = False)

    title = models.CharField(max_length=50, blank = False, null = False)

    description = models.CharField(max_length = 5000, blank = True, null = True)

    status = models.CharField(max_length = 50, blank = False, null = False, default=STATUS_CHOICE[0][0])

    created_by= models.ForeignKey(Profile, blank = False, null = False, on_delete=models.CASCADE)

    def __str__(self):
        return self.title

Ticketing/views.py
from .models import Ticket, Ticket_Comments
from .decorators import allowed_users, redirect_users
from Profile.models import Profile

from django.utils.decorators import method_decorator
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, get_object_or_404
from django.urls import reverse, reverse_lazy
from django.contrib.auth.models import User, Group
from django.views.generic import DetailView
from django.views.generic.edit import CreateView, UpdateView, DeleteView

@login_required(login_url='login')
@redirect_users
@allowed_users(allowed_roles=['Employee', 'Manager'])
def User_Ticketing(request):
    user_profile = Profile.objects.get(user = request.user)
    Ticket_database = Ticket.objects.filter(created_by = user_profile)

    context={
        'ticketing_list' : Ticket_database
    }

    return render(request, 'Ticketing/HuNetM_ViewTicketing.html', context)

@login_required(login_url='login')
@allowed_users(allowed_roles=['HR', 'HR manager'])
def HR_Ticketing(request):
    Ticket_database = Ticket.objects.all()

    context={
        'ticketing_list' : Ticket_database
    }

    return render(request, 'Ticketing/HuNetHR_ViewTicketing.html', context)

class Create_Ticketing(CreateView):
    model = Ticket
    fields = ['category', 'title', 'description', 'status']
    template_name = 'Ticketing/HuNet_CreateTicketing.html'
    success_url = reverse_lazy('Ticketing:User_Ticket')

    def form_valid(self, form):
        form.instance.created_by = self.request.user.profile
        print(form.cleaned_data)
        return super(Create_Ticketing, self).form_valid(form)

class Create_Comments(CreateView):
    model = Ticket_Comments
    fields = ['ticket', 'comment']  
    template_name = 'Ticketing/HuNet_CreateComments.html'
    success_url = reverse_lazy('Ticketing:User_Ticket')

    def form_valid(self, form):
        form.instance.user = self.request.user.profile
        print(form.cleaned_data)
        return super(Create_Comments, self).form_valid(form)

class Update_Ticketing(UpdateView):
    model = Ticket
    fields=['category', 'title', 'description', 'attachments', 'status']
    template_name = 'Ticketing/HuNet_CreateTicketing.html'
    success_url = reverse_lazy('Ticketing:User_Ticket')
    
    def form_valid(self, form):
        print(form.cleaned_data)
        return super(Update_Ticketing, self).form_valid(form)

class Update_Comments(UpdateView):
    model = Ticket_Comments
    fields = ['ticket', 'comment']
    template_name = 'Ticketing/HuNet_CreateComments.html'
    success_url = reverse_lazy('Ticketing:User_Ticket')

    def form_valid(self, form):
        print(form.cleaned_data)
        return super(Update_Comments, self).form_valid(form)

class Detail_Ticket(DetailView):
    template_name = 'Ticketing/HuNet_DetailTicket.html'
    queryset = Ticket.objects.all()

    def get_object(self):
        if self.request.user.is_authenticated:
            id = self.kwargs.get("pk")
            return Ticket.objects.get(id=id)
        
        else:
            return Ticket.objects.none()

class Delete_Comments(DeleteView):
    template_name='Ticketing/HuNet_DeleteComments.html'
    success_url = reverse_lazy('Ticketing:User_Ticket')

    def get_object(self):
        id = self.kwargs.get("pk")
        return get_object_or_404(Ticket_Comments, id=id)
    
class Delete_Ticket(DeleteView):
    template_name='Ticketing/HuNet_DeleteTicket.html'
    success_url = reverse_lazy('Ticketing:User_Ticket')

    def get_object(self):
        id = self.kwargs.get("pk")
        return get_object_or_404(Ticket, id=id)

Ticketing/templates/Ticketing/HuNetM_ViewTicketing.html
{%extends 'utilitypage.html'%}
{%load static%}
<head>
    <title>{%block title%}Ticketing{%endblock%}</title>
</head>
<body>
    <div class="wrapper">
        {%block content%}
        <a href="{% url 'Ticketing:Create_User_Ticket'%}">Create Ticket</a>

        <section class="View_ticketing">
            <table>
                <thead>
                    <tr>
                        <th scope="col">Ticketing ID</th>
                        <th scope="col">Category</th>
                        <th scope="col">Description</th>
                        <th scope="col">Comments count</th>
                        <th scope="col">Status</th>
                        <th scope="col" colspan="4">Actions</th>
                    </tr>
                </thead>

                <tbody>
                    {%for ticket in ticketing_list%}
                    <tr>
                        <td>{{ticket.id}}</td>
                        <td>{{ticket.category}}</td>
                        <td>{{ticket.title}}</td>
                        <td>{% with comments_count=ticket.Ticket_Comments_set.all%}{{comments_count|length}}{%endwith%}</td>
                        <td>{{ticket.status}}</td>
                        <td><a href="{% url 'Ticketing:Create_User_Comment' %}">Comment</a></td>
                        <td><a href="{% url 'Ticketing:Delete_Ticket' ticket.id %}">X</a></td>
                        <td><a href="{% url 'Ticketing:Detail_Ticket' ticket.id %}">See more</a></td>
                    </tr>
                    {%endfor%}
                </tbody>
            </table>
        </section>
        {%endblock%}
    </div>


</body>
</html>

Ticketing/templates/Ticketing/HuNet_CreateComments.html
<!--Inherit HTML from parent class 'sidenav'-->
{%extends 'sidenav.html'%}

<!--Load static is to load static files (HTML/CSS/Js)-->
{%load static%}
<!--To inform website version of HTML-->
<!DOCTYPE html>
<!--Inform website of language of HTML-->
<html lang="en">
<!--Header-->
<head>
    <!--HTML inheritance: overriding parent class title block(Django exclusive)-->
    <title>{%block title%}Ticket Comments Creation {%endblock%}</title>
</head>
<body>
    {%block content%}
    <!--HTML form, action on current page, use 'POST' method (secure)-->
    <form action= "" method = "POST">
        <!--Django Exclusive: CSRF token is a random, hard-to-guess string, prevent CSRF atk-->
        {%csrf_token%}
        
        <!--Generate form organised in paragraphs based on query on CreateCompetencies in GnC/views.py-->
        {{form.as_p}}
        <input type = 'submit' value = "Save Commments">
    </form>
    {%endblock%}
</body>
</html>

Ticketing/templates/Ticketing/HuNet_CreateTicketing.html
<!--Inherit HTML from parent class 'sidenav'-->
{%extends 'sidenav.html'%}

<!--Load static is to load static files (HTML/CSS/Js)-->
{%load static%}
<!--To inform website version of HTML-->
<!DOCTYPE html>
<!--Inform website of language of HTML-->
<html lang="en">
<!--Header-->
<head>
    <!--HTML inheritance: overriding parent class title block(Django exclusive)-->
    <title>{%block title%}Ticket Comments Creation {%endblock%}</title>
</head>
<body>
    {%block content%}
    <!--HTML form, action on current page, use 'POST' method (secure)-->
    <form action= "" method = "POST">
        <!--Django Exclusive: CSRF token is a random, hard-to-guess string, prevent CSRF atk-->
        {%csrf_token%}
        
        <!--Generate form organised in paragraphs based on query on CreateCompetencies in GnC/views.py-->
        {{form.as_p}}
        <input type = 'submit' value = "Save Commments">
    </form>
    {%endblock%}
</body>
</html>

Ticketing/templates/Ticketing/HuNet_DeleteComments.html
<!--Inherit HTML from parent class 'utiltiypage'-->
{%extends 'utilitypage.html'%}

<!--Load static is to load static files (HTML/CSS/Js)-->
{%load static%}
<!--To inform website version of HTML-->
<!DOCTYPE html>
<!--Inform website of language of HTML-->
<html lang="en">
<!--Header-->
<head>

    <!--HTML inheritance: overriding parent class title block(Django exclusive)-->
    <title>{%block title%}Comments Deletion {%endblock%}</title>
</head>
<body>
    {%block content%}
    <!--HTML form, action on current page, use 'POST' method (secure)-->
    <form action="" method='POST'>
        <!--Django Exclusive: CSRF token is a random, hard-to-guess string, prevent CSRF atk-->
        {%csrf_token%}

        <!--Things within double braces are object instances within a queryset, so in this case I am accessing object's summary-->
        <h5>Do you want to delete "{{object.summary}}"?</h5>

        <div class = "row m-0 justify-content-end">
            <a class = "btn btn-danger mr-2" type = "button" href="{% url 'Ticketing:User_Ticket%}">Cancel</a>
            <input class = "btn btn-primary"type ="submit" value = "Confirm">
        </div>

        <!--**Dynamic routing to 'GnC:User_GnC' template -->

    </form>

    {%endblock%}
</body>

Ticketing/templates/Ticketing/HuNet_DeleteTicket.html
<!--Inherit HTML from parent class 'utiltiypage'-->
{%extends 'utilitypage.html'%}

<!--Load static is to load static files (HTML/CSS/Js)-->
{%load static%}
<!--To inform website version of HTML-->
<!DOCTYPE html>
<!--Inform website of language of HTML-->
<html lang="en">
<!--Header-->
<head>
      <!--Meta to improve SEO-->
    <meta charset="UTF-8">
    <meta name="viewport" content="width=<device-width>, initial-scale=1.0">

    <!--HTML inheritance: overriding parent class title block(Django exclusive)-->
    <title>{%block title%}Ticket Deletion{%endblock%}</title>
</head>
<body>
    {%block content%}
    <!--HTML form, action on current page, use 'POST' method (secure)-->
    <form action="" method='POST'>
        <!--Django Exclusive: CSRF token is a random, hard-to-guess string, prevent CSRF atk-->
        {%csrf_token%}

        <!--Things within double braces are object instances within a queryset, so in this case I am accessing object's summary-->
        <h4>Do you want to delete "{{object.summary}}"?</h4>

        <div class = "row justify-content-end m-0">
            <a class = "btn btn-danger mr-2" type = "button" href="{% url 'Ticketing:User_Ticket'%}">Cancel</a>
            <input class = "btn btn-primary" type ="submit" value = "Confirm">
            <!--**Dynamic routing to 'GnC:User_GnC' template -->
    
        </div>
    </form>
    {%endblock%}
</body>

Ticketing/templates/Ticketing/HuNet_DetailTicket.html
<!--Inherit HTML from parent class 'utiltiypage'-->
{%extends 'utilitypage.html'%}

<!--Load static is to load static files (HTML/CSS/Js)-->
{%load static%}
<!--To inform website version of HTML-->
<!DOCTYPE html>
<!--Inform website of language of HTML-->
<html lang="en">
<!--Header-->
<head>

    <!--HTML inheritance: overriding parent class title block(Django exclusive)-->
    <title>{%block title%}Ticket Details{%endblock%}</title>
</head>
<body>
    <!--HTML inheritance: overriding parent class content block(Django exclusive)-->
    {%block content%}

    <a href="{%url 'Ticketing:Create_User_Comment'%}">Comment</a>
    <!--Things within double braces are object instances within a queryset.-->
    <!--Accessing ticket category-->
    <p>Ticket category: {{object.category}}</p>
    <!--Accessing ticket title-->
    <p>Ticket Title: {{object.title}}</p>
    <!--Accessing ticket description-->
    <p>Ticket description: {{object.description}}</p>
    <!--Accessing ticket status-->
    <p>Ticket Status: {{object.status}}</p>
    <!--Accessing ticket creator-->
    <p>Created by: {{object.created_by.name}}</p>
    
    {%for comments in object.Ticket_Comments_set.all%}
    <p>{{comments.user.name}}: {{comments.comment}}, created on {{comments.created_on}}</p>
    {%endfor%}
    {%endblock%}
</body>